on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-next
          path: .next

  test: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v6
      - run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: build-next
          path: .next
      - uses: cypress-io/github-action@v6
